
import { Maybe, Scalars } from "@/gql/graphql";

export interface CommonRecentOrdersProps {
  children?: React.ReactNode;
__typename?: 'CommonRecentOrders';
CustomCSS?: Maybe<Scalars['String']['output']>;
Id?: Maybe<Scalars['String']['output']>;
IsLayout?: Maybe<Scalars['Boolean']['output']>;
NumberOfRecords?: Maybe<Scalars['Int']['output']>;
ParentId?: Maybe<Scalars['String']['output']>;
Type?: Maybe<Scalars['String']['output']>;
Zone?: Maybe<Scalars['String']['output']>;
_id?: Maybe<Scalars['String']['output']>;
};

export interface IOrder {
  uri: string;
  id: string;
  erpOrderNumber: string;
  webOrderNumber: string;
  orderDate: string;
  status: string;
  statusDisplay: string;
  customerNumber: string;
  customerSequence: string;
  customerPO: string;
  currencyCode: string;
  currencySymbol: string;
  terms: string;
  shipCode: string;
  salesperson: string;
  btCompanyName: string;
  btAddress1: string;
  btAddress2: string;
  btAddress3: string;
  btAddress4: string;
  billToCity: string;
  billToState: string;
  billToPostalCode: string;
  btCountry: string;
  stCompanyName: string;
  stAddress1: string;
  stAddress2: string;
  stAddress3: string;
  stAddress4: string;
  shipToCity: string;
  shipToState: string;
  shipToPostalCode: string;
  stCountry: string;
  notes: string;
  productTotal: number;
  orderSubTotal: number;
  discountAmount: number;
  orderDiscountAmount: number;
  productDiscountAmount: number;
  shippingAndHandling: number;
  shippingCharges: number;
  handlingCharges: number;
  otherCharges: number;
  taxAmount: number;
  orderTotal: number;
  modifyDate: string;
  requestedDeliveryDateDisplay: string | null;
  orderLines: unknown[];
  orderPromotions: unknown[];
  shipmentPackages: unknown[];
  returnReasons: string[];
  orderHistoryTaxes: unknown[];
  productTotalDisplay: string;
  orderSubTotalDisplay: string;
  orderTotalDisplay: string;
  orderGrandTotalDisplay: string;
  discountAmountDisplay: string;
  orderDiscountAmountDisplay: string;
  productDiscountAmountDisplay: string;
  taxAmountDisplay: string;
  totalTaxDisplay: string;
  shippingAndHandlingDisplay: string;
  shippingChargesDisplay: string;
  handlingChargesDisplay: string;
  otherChargesDisplay: string;
  canAddToCart: boolean;
  canAddAllToCart: boolean;
  showTaxAndShipping: boolean;
  shipViaDescription: string | null;
  fulfillmentMethod: string;
  customerVatNumber: string;
  vmiLocationId: string | null;
  vmiLocationName: string | null;
  properties: Record<string, unknown>;
}