export interface OrderDetail {
  uri?: string;
  id?: string;
  erpOrderNumber?: string;
  webOrderNumber?: string;
  orderDate?: string;
  status?: string;
  statusDisplay?: string;
  customerNumber?: string;
  customerSequence?: string;
  customerPO?: string;
  currencyCode?: string;
  currencySymbol?: string;
  terms?: string;
  shipCode?: string;
  salesperson?: string;
  btCompanyName?: string;
  btAddress1?: string;
  btAddress2?: string;
  btAddress3?: string;
  btAddress4?: string;
  billToCity?: string;
  billToState?: string;
  billToPostalCode?: string;
  btCountry?: string;
  stCompanyName?: string;
  stAddress1?: string;
  stAddress2?: string;
  stAddress3?: string;
  stAddress4?: string;
  shipToCity?: string;
  shipToState?: string;
  shipToPostalCode?: string;
  stCountry?: string;
  notes?: string;
  orderLines?: CartProduct[];
  productTotal?: number;
  orderSubTotal?: number;
  discountAmount?: number;
  orderDiscountAmount?: number;
  productDiscountAmount?: number;
  shippingAndHandling?: number;
  shippingCharges?: number;
  handlingCharges?: number;
  otherCharges?: number;
  taxAmount?: number;
  orderTotal?: number;
  modifyDate?: string;
  requestedDeliveryDateDisplay?: string | null;
  orderPromotions?: Array<any>;
  shipmentPackages?: Array<any>;
  returnReasons?: Array<string>;
  orderHistoryTaxes?: Array<any>;
  productTotalDisplay?: string;
  orderSubTotalDisplay?: string;
  orderTotalDisplay?: string;
  orderGrandTotalDisplay?: string;
  discountAmountDisplay?: string;
  orderDiscountAmountDisplay?: string;
  productDiscountAmountDisplay?: string;
  taxAmountDisplay?: string;
  totalTaxDisplay?: string;
  shippingAndHandlingDisplay?: string;
  shippingChargesDisplay?: string;
  handlingChargesDisplay?: string;
  otherChargesDisplay?: string;
  canAddToCart?: boolean;
  canAddAllToCart?: boolean;
  showTaxAndShipping?: boolean;
  shipViaDescription?: string;
  fulfillmentMethod?: string;
  customerVatNumber?: string;
  vmiLocationId?: string | null;
  vmiLocationName?: string | null;
  properties?: Record<string, unknown>;
}

export interface CartProduct {
  uri?: string | null;
  id?: string;
  productId?: string;
  productUri?: string;
  mediumImagePath?: string;
  altText?: string;
  productName?: string | null;
  manufacturerItem?: string;
  customerName?: string | null;
  shortDescription?: string;
  productErpNumber?: string;
  customerProductNumber?: string;
  requiredDate?: string | null;
  lastShipDate?: string | null;
  customerNumber?: string;
  customerSequence?: string;
  lineType?: string;
  status?: string;
  lineNumber?: number;
  releaseNumber?: number;
  linePOReference?: string;
  description?: string;
  warehouse?: string;
  notes?: string;
  qtyOrdered?: number;
  qtyShipped?: number;
  unitOfMeasure?: string;
  unitOfMeasureDisplay?: string | null;
  unitOfMeasureDescription?: string | null;
  availability?: {
    messageType?: number;
    message?: string | null;
    requiresRealTimeInventory?: boolean;
  };
  inventoryQtyOrdered?: number;
  inventoryQtyShipped?: number;
  unitPrice?: number;
  unitNetPrice?: number;
  extendedUnitNetPrice?: number;
  discountPercent?: number;
  discountAmount?: number;
  unitDiscountAmount?: number;
  promotionAmountApplied?: number;
  totalDiscountAmount?: number;
  lineTotal?: number;
  totalRegularPrice?: number;
  unitListPrice?: number;
  unitRegularPrice?: number;
  unitCost?: number;
  orderLineOtherCharges?: number;
  taxRate?: number;
  taxAmount?: number;
  returnReason?: string | null;
  rmaQtyRequested?: number;
  rmaQtyReceived?: number;
  unitPriceDisplay?: string;
  unitNetPriceDisplay?: string;
  extendedUnitNetPriceDisplay?: string;
  discountAmountDisplay?: string;
  unitDiscountAmountDisplay?: string;
  promotionAmountAppliedDisplay?: string;
  totalDiscountAmountDisplay?: string;
  lineTotalDisplay?: string;
  totalRegularPriceDisplay?: string;
  unitListPriceDisplay?: string;
  unitRegularPriceDisplay?: string;
  unitCostDisplay?: string;
  orderLineOtherChargesDisplay?: string;
  costCode?: string | null;
  canAddToCart?: boolean;
  isActiveProduct?: boolean;
  sectionOptions?: string | null;
  salePriceLabel?: string;
  canAddToWishlist?: boolean;
  brand?: string | null;
  netPriceWithVat?: number;
  netPriceWithVatDisplay?: string;
  unitPriceWithVat?: number;
  unitPriceWithVatDisplay?: string;
  vmiBinNumber?: string | null;
  vmiBinId?: string | null;
  isActiveVmiBin?: boolean;
  isDiscontinued?: boolean;
  properties?: object;
}
