name: Version Bump

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Determine version bump type
        id: bump-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          if [[ "$PR_TITLE" == *"BREAKING CHANGE"* || "$PR_TITLE" == *"!:"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
            echo "Detected BREAKING CHANGE - will perform major bump"
          elif [[ "$PR_TITLE" == "feat:"* || "$PR_TITLE" == "feature:"* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
            echo "Detected new feature - will perform minor bump"
          else
            echo "type=patch" >> $GITHUB_OUTPUT
            echo "Detected fix or other change - will perform patch bump"
          fi

      - name: Bump version
        run: |
          BUMP_TYPE="${{ steps.bump-type.outputs.type }}"
          npm version $BUMP_TYPE --no-git-tag-version

          # Get the new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"

          # Commit the version change
          git add package.json
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push
